name: Cypress Tests Run on Pipeline

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ou a versão do Node.js que você está utilizando

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome # Você pode alterar isso para 'firefox' ou 'edge'

      # Opcional: Upload resultados dos testes e screenshots como artefatos
      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots/**/*, cypress/videos/**/*
